const JENISORDERMUATAN = 174;
const JENISORDERBONGKARAN = 175;
const JENISORDERANIMPORT = 176;
const JENISORDERANEXPORT = 177;
const STATUSDATAPENDUKUNGYA = 14;
const STATUSDATAPENDUKUNGTIDAK = 15;
const JENISORDERMUATANNAMA = 'MUATAN';
const JENISORDERBONGKARANNAMA = 'BONGKARAN';
const JENISORDERIMPORTNAMA = 'IMPORT';
const JENISORDEREKSPORTNAMA = 'EKSPORT';

export {
  JENISORDERMUATAN,
  JENISORDERBONGKARAN,
  JENISORDERANIMPORT,
  JENISORDERANEXPORT,
  STATUSDATAPENDUKUNGYA,
  STATUSDATAPENDUKUNGTIDAK,
  JENISORDERMUATANNAMA,
  JENISORDERBONGKARANNAMA,
  JENISORDERIMPORTNAMA,
  JENISORDEREKSPORTNAMA
};
