const JENISORDERMUATAN = 1;
const JENISORDERBONGKARAN = 2;
const JENISORDERANIMPORT = 3;
const JENISORDERANEXPORT = 4;

const JENISORDERMUATANNAMA = 'MUATAN';
const JENISORDERBONGKARANNAMA = 'BONGKARAN';
const JENISORDERIMPORTNAMA = 'IMPORT';
const JENISORDEREKSPORTNAMA = 'EKSPORT';

const BIAYAEMKLLAINLAIN = 12;

const BIAYAEMKLDEFAULT = 'BIAYA LAIN LAIN';

const STATUSDATAPENDUKUNGYA = 14;
const STATUSDATAPENDUKUNGTIDAK = 15;

export {
  JENISORDERMUATAN,
  JENISORDERBONGKARAN,
  JENISORDERANIMPORT,
  JENISORDERANEXPORT,
  BIAYAEMKLLAINLAIN,
  BIAYAEMKLDEFAULT,
  JENISORDERMUATANNAMA,
  JENISORDERBONGKARANNAMA,
  STATUSDATAPENDUKUNGTIDAK,
  JENISORDERIMPORTNAMA,
  JENISORDEREKSPORTNAMA
};
